### ISSUE TITLE
Incorrect form control styling when in pristine state

### ISSUE THREAD

**Issue by paninics** [creativetimofficial/material-dashboard-pro-angular#217]
Here's a sample code from a component:
```  typescript
loginForm: FormGroup;

constructor(private fb: FormBuilder) { }

ngOnInit() {
  this.loginForm = this.fb.group({
  email: '', // or set to null
  // email: ['', [Validators.email, Validators.required]],
  password: ['', Validators.required]
});
```
And here's the result:

![temp](https://user-images.githubusercontent.com/23061690/38124824-b5e6e77e-3399-11e8-98a6-bd788abc0caa.png)

Notice that the email has no default value and no validators. When the form loads, i.e. it is in a [pristine state](https://angular.io/guide/form-validation#control-status-css-classes), the email shows up in success styling (i.e. the green color). This I believe is incorrect as the user has not even begin to enter the data (i.e the touched / dirty state). If we go with the existing logic, the password should have shown in failure styling (i.e. the red color) but it isn't and that I believe is the right behavior.

**Comment by chelaruc** [comment]
fixed in v2.0.1

**Comment by paninics** [comment]
With v2.0.1, I still see the issue. Can you please point out, what was the exact fix so that I can double check on my end.

**Comment by chelaruc** [comment]
@paninics I used your above code and it is working for me. Can you give me another example?

**Comment by Shakell** [comment]
I met the same problem, could you please point out how to fix it so I can resolve it in my project.

**Comment by Shakell** [comment]
I downloaded the version 2.0.1, there is the same problem. If you use a formControl without required, it shows always the green line. It's not reasonable. Please fix it.

**Comment by chelaruc** [comment]
@paninics @Shakell please change the files from the attached archive with the current files. This will be fixed in the next version.
[changes.zip](https://github.com/creativetimofficial/material-dashboard-pro-angular/files/1967475/changes.zip)
